
package parcial2.View;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;


public class Login extends javax.swing.JFrame {
    
 

    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRegistrarseop = new javax.swing.JLabel();
        lblIniciosesion = new javax.swing.JLabel();
        txtnombreR = new javax.swing.JLabel();
        txtPassR = new javax.swing.JLabel();
        nameRegistro = new javax.swing.JTextField();
        passRegistro = new javax.swing.JTextField();
        btnRegistro = new javax.swing.JButton();
        namRegistro1 = new javax.swing.JLabel();
        passRegistro1 = new javax.swing.JLabel();
        nameSesion = new javax.swing.JTextField();
        passSesion = new javax.swing.JTextField();
        btnSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblRegistrarseop.setText("Registrarse");

        lblIniciosesion.setText("Iniciar Sesion");

        txtnombreR.setText("Nombre: ");

        txtPassR.setText("Contraseña: ");

        passRegistro.addActionListener(this::passRegistroActionPerformed);

        btnRegistro.setText("Registro");
        btnRegistro.addActionListener(this::btnRegistroActionPerformed);

        namRegistro1.setText("Nombre: ");

        passRegistro1.setText("Contraseña: ");

        btnSesion.setText("Iniciar sesion");
        btnSesion.addActionListener(this::btnSesionActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(lblRegistrarseop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIniciosesion)
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnombreR)
                    .addComponent(txtPassR))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistro)
                    .addComponent(passRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namRegistro1)
                    .addComponent(passRegistro1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSesion)
                    .addComponent(passSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegistrarseop)
                    .addComponent(lblIniciosesion))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnombreR)
                            .addComponent(nameRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPassR)
                            .addComponent(passRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addComponent(btnRegistro))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namRegistro1)
                            .addComponent(nameSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passRegistro1)
                            .addComponent(passSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addComponent(btnSesion)))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSesionActionPerformed
        ScreenManager.abrirRuleta(this);
    }//GEN-LAST:event_btnSesionActionPerformed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        ScreenManager.abrirRuleta(this);
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void passRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passRegistroActionPerformed

    public JButton getBtnRegistro() {
        return btnRegistro;
    }

    public void setBtnRegistro(JButton btnRegistro) {
        this.btnRegistro = btnRegistro;
    }

    public JButton getBtnSesion() {
        return btnSesion;
    }

    public void setBtnSesion(JButton btnSesion) {
        this.btnSesion = btnSesion;
    }

    public JLabel getLblIniciosesion() {
        return lblIniciosesion;
    }

    public void setLblIniciosesion(JLabel lblIniciosesion) {
        this.lblIniciosesion = lblIniciosesion;
    }

    public JLabel getLblRegistrarseop() {
        return lblRegistrarseop;
    }

    public void setLblRegistrarseop(JLabel lblRegistrarseop) {
        this.lblRegistrarseop = lblRegistrarseop;
    }

    public JLabel getNamRegistro1() {
        return namRegistro1;
    }

    public void setNamRegistro1(JLabel namRegistro1) {
        this.namRegistro1 = namRegistro1;
    }

    public JTextField getNameRegistro() {
        return nameRegistro;
    }

    public void setNameRegistro(JTextField nameRegistro) {
        this.nameRegistro = nameRegistro;
    }

    public JTextField getNameSesion() {
        return nameSesion;
    }

    public void setNameSesion(JTextField nameSesion) {
        this.nameSesion = nameSesion;
    }

    public JTextField getPassRegistro() {
        return passRegistro;
    }

    public void setPassRegistro(JTextField passRegistro) {
        this.passRegistro = passRegistro;
    }

    public JLabel getPassRegistro1() {
        return passRegistro1;
    }

    public void setPassRegistro1(JLabel passRegistro1) {
        this.passRegistro1 = passRegistro1;
    }

    public JLabel getTxtPassR() {
        return txtPassR;
    }

    public void setTxtPassR(JLabel txtPassR) {
        this.txtPassR = txtPassR;
    }

    public JLabel getTxtnombreR() {
        return txtnombreR;
    }

    public void setTxtnombreR(JLabel txtnombreR) {
        this.txtnombreR = txtnombreR;
    }

    
    

    /**
     * @param args the command line arguments
     */
    public void setPassSesion(JTextField passSesion) {
        this.passSesion = passSesion;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    @Override
    public String toString() {
        return "Login{" + "btnRegistro=" + btnRegistro + ", btnSesion=" + btnSesion + ", lblIniciosesion=" + lblIniciosesion + ", lblRegistrarseop=" + lblRegistrarseop + ", namRegistro1=" + namRegistro1 + ", nameRegistro=" + nameRegistro + ", nameSesion=" + nameSesion + ", passRegistro=" + passRegistro + ", passRegistro1=" + passRegistro1 + ", passSesion=" + passSesion + ", txtPassR=" + txtPassR + ", txtnombreR=" + txtnombreR + '}';
    }



    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistro;
    private javax.swing.JButton btnSesion;
    private javax.swing.JLabel lblIniciosesion;
    private javax.swing.JLabel lblRegistrarseop;
    private javax.swing.JLabel namRegistro1;
    private javax.swing.JTextField nameRegistro;
    private javax.swing.JTextField nameSesion;
    private javax.swing.JTextField passRegistro;
    private javax.swing.JLabel passRegistro1;
    private javax.swing.JTextField passSesion;
    private javax.swing.JLabel txtPassR;
    private javax.swing.JLabel txtnombreR;
    // End of variables declaration//GEN-END:variables
}
